label2color = {
  "birthday": "azure",
  "gender": "brown",
  "experience": "red",
  "experience_role": "darkred",
  "experience_years": "ivory",
  "education": "violet",
  "hard_skills": "pink",
  "soft_skills": "lightpink",
  "certifications": "plum",
  "degree": "cyan",
  "seminars": "lavender",
  "training": "green",
  "training_location": "forestgreen",
  "experience_h": "indianred",
  "education_h": "indigo",
  "skills_h": "hotpink",
  "certifications_h": "maroon",
  "seminars_h": "lavenderblush",
  "training_h": "seagreen",
  "other": "grey"
}